FROM node:20.12.2

WORKDIR /app

RUN chown node:node /app

USER node

COPY --chown=node:node app/package.json package.json
COPY --chown=node:node app/package-lock.json package-lock.json

RUN npm ci

COPY --chown=node:node app/. .

RUN make build

ENV NODE_ENV=production
EXPOSE 8080

CMD ["make", "start"]