services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - NODE_ENV=development
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command: make dev

  caddy:
    image: caddy:2.7.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

volumes:
  node_modules: